[package]
name = "core"
version = "0.0.1"

[dependencies]
hex = "0.4.3"
ethereum-types = "0.11.0"
parity-secp256k1 = "0.7.0"
keccak-hash = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
rlp = "0.5"

[dev-dependencies]
hex-literal = "0.3.1"
